settings:
  commit_msg: "update(activity): Update README"
  url_text: "`{REPO}{ID}`"
  date:
    timezone: "Europe/Paris"
    format: "dd/mm HH:MM"
messages:
  comment: "`{DATE}` Commented on {URL} in {REPO}"
  issue_opened: "`{DATE}` Opened issue {URL} in {REPO}"
  issue_closed: "`{DATE}` Closed issue {URL} in {REPO}"
  pr_opened: "`{DATE}` Opened PR {URL} in {REPO}"
  pr_closed: "`{DATE}` Closed PR {URL} in {REPO}"
  pr_merged: "`{DATE}` Merged PR {URL} in {REPO}"
  create_repo: "`{DATE}` Created repository {REPO}"
  fork_repo: "`{DATE}` Forked {URL} from {REPO}"
  wiki_create: "`{DATE}` Create new wiki page `{WIKI}` in {REPO}"
  added_member: "`{DATE}` Become contributor on {REPO}"
  changes_approved: "`{DATE}` Approved {URL} in {REPO}"
  changes_requested: "`{DATE}` Request changes on {URL} in {REPO}"
  new_release: "`{DATE}` Released {URL} on {REPO}"
  new_star: "`{DATE}` Starred {URL} in {REPO}"