settings:
  commit_msg: "update(activity): Update README"
  url_text: "`{REPO}{ID}`"
  date:
    timezone: "Europe/Paris"
    format: "dd/mm HH:MM"
messages:
  comment: "`{DATE}` Commented on `{ID}` in {REPO}"
  issue_opened: "`{DATE}` Opened issue `{ID}` in {REPO}"
  issue_closed: "`{DATE}` Closed issue `{ID}` in {REPO}"
  pr_opened: "`{DATE}` Opened PR `{ID}` in {REPO}"
  pr_closed: "`{DATE}` Closed PR `{ID}` in {REPO}"
  pr_merged: "`{DATE}` Merged PR `{ID}` in {REPO}"
  create_repo: "`{DATE}` Created repository {REPO}"
  fork_repo: "`{DATE}` Forked `{FORK}` from {REPO}"
  wiki_create: "`{DATE}` Create new wiki page `{WIKI}` in {REPO}"
  added_member: "`{DATE}` Become contributor on {REPO}"
  changes_approved: "`{DATE}` Approved `{ID}` in {REPO}"
  changes_requested: "`{DATE}` Request changes on `{ID}` in {REPO}"
  new_release: "`{DATE}` Released `{ID}` on {REPO}"
  new_star: "`{DATE}` Starred `{ID}` in {REPO}"