settings:
  commit_msg: "update(activity): Update README"
  url_text: "`{ID}`"
  date:
    timezone: "Europe/Paris"
    format: "dd/mm HH:MM"
messages:
  comment: "`{DATE}` ![comment] Commented on {URL} in {REPO}"
  issue_opened: "`{DATE}` ![issueOpened] Opened issue {URL} in {REPO}"
  issue_closed: "`{DATE}` ![issueClosed] Closed issue {URL} in {REPO}"
  pr_opened: "`{DATE}` ![prOpened] Opened PR {URL} in {REPO}"
  pr_closed: "`{DATE}` ![prClosed] Closed PR {URL} in {REPO}"
  pr_merged: "`{DATE}` ![prMerged] Merged PR {URL} in {REPO}"
  create_repo: "`{DATE}` ![repoCreated] Created repository {REPO}"
  fork_repo: "`{DATE}` ![fork] Forked {URL} from {REPO}"
  wiki_create: "`{DATE}` ![wiki] Create new wiki page `{WIKI}` in {REPO}"
  added_member: "`{DATE}` ![people] Become contributor on {REPO}"
  changes_approved: "`{DATE}` ![approved] Approved {URL} in {REPO}"
  changes_requested: "`{DATE}` ![changesRequested] Request changes on {URL} in {REPO}"
  new_release: "`{DATE}` ![new_release] Released {URL} on {REPO}"
  new_star: "`{DATE}` ![star] Starred {URL} in {REPO}"