name: Resize SVG

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  resize-svg:
    name: Update SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: enimaloc/svg-sizer@master
        with:
          output-folder: "./res"
          input-file: "svg-input.txt"
          dimension: "16x16"
      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          default_author: github_actions